display_name: StitchTV
package_name: stitchtv
maintainer:
  name: GutsGo
priority: optional
section: x11
installed_size: 24400
essential: false
icon: assets/logo.png

keywords:
  - StitchTV

generic_name: StitchTV

categories:
  - Media

startup_notify: true
